server:
  port: 8060
spring:
  application:
    name: SourceQuartz
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: 账号
    password: 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: 数据库地址
mybatis-plus:
  # 指定别名扫描路径，这个路径后续在client-common模块里定义，该路径下的实体类将自动配置别名，默认为类名首字母小写。配置别名后，便可以直接在MyBatis XML文件里使用了
  type-aliases-package: com.source.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 指定为null，否则再插入空值时会报“无效的列类型”错误；
    jdbc-type-for-null: null
  global-config:
    # 设置为false关闭MyBatis Plus Banner打印
    banner: false

source:
  # AOP记录用户操作日志，true开启，false关闭
  open-aop-log: true
  # 是否在控制台打印 sql语句
  shows_ql: true